### ISSUE TITLE
Regression: inserting to the left of a root node

### ISSUE THREAD

**Issue by schanzer** [bootstrapworld/codemirror-blocks#427] opened 2021-09-27 16:57 UTC
1. Open the demo editor, and convert to block mode
2. To the left of `(+ 1 2)`, insert the letter `a`

EXPECTED: `a` is shown as a top-level literal on its own line, with focus
ACTUAL: editor breaks

**Comment by pcardune** [comment] 2021-11-01 19:11
Ok, I'm not sure I'm reproducing the same thing that you were, but there is still a bug and it has to do with comments.

This is the code being edited.
```rkt
#| a child of this expression has a nested comment |#
(+ 1 #| this is a nested comment |# 2)
```
when you then click to the left of the `(+ 1 2)` expression so you are still on the same line, it leads to an `OverwriteEdit`, which is for editing code at the top-level of the document and not somewhere in the AST. Then you type in some letters like `abc` and hit enter. We create a change object which inserts the text "abc" before the comment. Then in `OverwriteEdit.toChangeObject`, the code that determines whether or not a newline should be inserted, doesn't take into account the possibility of there being a comment, which doesn't appear as a top-level node in the AST. So it thinks the code is being inserted on an empty line and the change that's made looks like this:

```rkt
abc#| a child of this expression has a nested comment |#
(+ 1 #| this is a nested comment |# 2)
```

which doesn't parse.

This could be fixed by having `OverwriteEdit.toChangeObject` also look for comments associated with a node, but I'm not sure that's the right fix. It would be helpful to know more about how the commenting feature is supposed to work. Was this working somehow before @schanzer ?

**Comment by schanzer** [comment] 2021-11-02 21:00
Ah! That makes total sense. Reviewing the PR now...

**Closed** 2021-11-02 21:01 UTC
Labels: bug
