### ISSUE TITLE
Tests that rely on events dispatched to quarantine nodes fail

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#120] opened 2018-07-17 04:32 UTC
On my computer, this test case:

    it('should save a valid, edited node on blur', function(done) {
      this.literal.el.dispatchEvent(dblclick());
      setTimeout(() => {
        let selection = window.getSelection();
        expect(selection.rangeCount).toEqual(1);
        let range = selection.getRangeAt(0);
        range.deleteContents();
        range.insertNode(document.createTextNode('9'));
        expect(this.cm.getValue()).toEqual('11');
        document.activeElement.dispatchEvent(blur());
        expect(this.cm.getValue()).toEqual('9');
        expect(this.blocks.hasInvalidEdit).toBe(false); // This is true
        done();
      }, DELAY);
    });

fails with the following error message:

    Chrome 64.0.3282 (Linux 0.0.0) The CodeMirrorBlocks Class events, should save a valid, edited node on blur FAILED
    	Expected true to be false.
    	    at <Jasmine>
    	    at webpack:///spec/justin.js:105:43 <- spec/index.js:25:97579
    Chrome 64.0.3282 (Linux 0.0.0): Executed 1 of 1 (1 FAILED) ERROR (0.149 secs / 0.796 secs)
    npm ERR! Test failed.  See above for more details.

Here's what happens:

1. The test case triggers a `blur` event, via this line:
   `document.activeElement.dispatchEvent(blur());`
2. The `onblur` handler activates and calls the `saveEdit` function in
   `blocks.js`. So far so good.
3. The `saveEdit` function gets down to this line:
   `nodeEl.parentNode.removeChild(nodeEl);`
4. Which, as it's executing but before removing the child, triggers a
   `blur` event.
5. The `onblur` handler activates again and calls `saveEdit`, which
   carries forth, dutifully executes the
   `nodeEl.parentNode.removeChild(nodeEl)` line as well as the rest of
   the function, and returns.
6. This second `onblur` event has now successfully completed, and
   removed the child.
7. The first `onblur` event tries to actually remove the child and
   fails to, as it is no longer a child of that parent, throwing an
   error and causing the test case to fail.

There's a [SO post discussing this surprising behavior](https://stackoverflow.com/questions/11600301/removing-an-element-through-the-parentnode-removechild-throws-a-dom-exception-8). I'm not sure why this would happen only for me.

See also the [MDN page on `.removeChild`](https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild), which mentions this behavior.

Likewise, these two test cases appear to fail for me for a similarish reason:

        it('should save whiteSpace on blur', function(done) {
          this.whiteSpaceEl.dispatchEvent(dblclick());
          setTimeout(() => {
            // A blur event happens around here, but BEFORE the next line.
            let quarantine = document.querySelectorAll('.blocks-editing')[0];
            // quarantine is undefined
            let selection = window.getSelection();
            expect(selection.rangeCount).toEqual(1);
            let range = selection.getRangeAt(0);
            range.deleteContents();
            range.insertNode(document.createTextNode('4253'));
            // This line fails, because `quarantine` is undefined
            quarantine.dispatchEvent(blur());
            expect(this.cm.getValue()).toBe('(+ 1 4253 2) (+)');
            expect(this.blocks.hasInvalidEdit).toBe(false);
            done();
          }, DELAY);
        });

        it('should not save anything & set all error state', function() {
          // A blur event happens around here
          let quarantine = document.querySelectorAll('.blocks-editing')[0];
          expect(this.cm.replaceRange).not.toHaveBeenCalled();
          expect(quarantine.classList).toContain('blocks-error');
          expect(quarantine.title).toBe('Error: parse error');
          expect(this.blocks.hasInvalidEdit).toBe(true);
        });

They seem to fail due to stray `blur` events. As far as I can tell
they're coming from `handlers.default.call(this, node, event);` in the
`nodeEventHandler` wrapper around calls to `insertionQuarantine` when
handling a double click.

**Comment by schanzer** [comment] 2018-07-24 17:34
Thanks for chasing this down -- remember how I said that sometimes I need to refresh the testing window to get all tests to pass? THIS is the issue. What baffles me is why this only show up in the test harness, and not in the actual editor when I run it. Try inserting a `console.log(event)` at the top of `saveEdit`: I can't get it to show being double-called for the life of me.

But assuming you're right I don't see a way around this, other than to wrap the `removeChild` call in a try/catch. That way we can rely on the second `saveEdit` call to do the right thing, and fail gracefully. What do you think?

**Comment by schanzer** [comment] 2018-07-30 12:09
Update: the issue isn't the double-blur. It's that the quarantine node returned by `insertionQuaratine()` wasn't being rendered fast enough to be captured via `document.activeElement` or `document.querySelector` in the test harness. As a result, when we dispatch on that node, we're getting errors. Renaming the issue to match.

Trying a different approach using Jasmine's ability to grab the result of a function that's being spied upon.

**Comment by schanzer** [comment] 2018-07-30 13:14
@justinpombrio try this and see where it gets you. I still get unreliable test passage, but now for reasons having to do with Jasmine, rather than the DOM.

**Comment by schanzer** [comment] 2018-07-30 20:25
Which test is failing for you? It's possibly I'm misunderstanding how spies work in Jasmine. It might be that we need to re-spy inside each test, since `hasBeenCalled()` might refer to whether or not the functions has been called _globally_

**Comment by schanzer** [comment] 2018-07-31 19:36
Further progress in b7fe17fa781bb94d686a3b4fcec249bd3dac914a. We've got it narrowed down to two tests, and what might be a bug in Karma/Jasmine. Spies confirm that the node handed to `saveEdit` has a `textContent` value of the inserted text. However, adding a console.log to saveEdit after the first line of code shows that `node.textContent` is the empty string!

**Comment by justinpombrio** [comment] 2018-07-31 20:53
If I've tracked this down correctly, the call to `saveEdit` comes before, not after, the edit in this test. The issue is that a singleclick event is coming from nowhere and changing the focus away before the edit can happen; hence the empty textContent. More info [here](https://github.com/bootstrapworld/codemirror-blocks/issues/123)

**Comment by schanzer** [comment] 2018-08-02 16:46
Now that most of these are stomped, and we have a dedicated issue for the remaining two, I'm marking this as closed.

**Closed by schanzer** 2018-08-02 16:46 UTC
