### ISSUE TITLE
Interaction between languages

### ISSUE THREAD

**Issue by prestontw** [bootstrapworld/codemirror-blocks#233] opened 2019-04-01 20:48 UTC
It looks like some name-clobbering or cyclic dependencies are caused by using more than one language.

# Steps to reproduce:
- Add `wescheme` in `new-pyret-editor-example.js` in `examples/` (https://github.com/bootstrapworld/codemirror-blocks/commit/1e5c25a75ad2dfacd64528beced543c3232a6555)
- `npm start` and navigate to `http://localhost:8080/new-pyret-editor.html`
- open the dev console and verify that you get this error:
```
TypeError: Cannot read property 'call' of undefined
    at Grammar.applyAction (rnglr.js:1322)
    ...
```
This is reported as coming from Pyret's battle-hardened parser, which doesn't make sense.

# Workaround
Import order might be important here. For me, moving `pyret` after `wescheme` works.

**Comment by justinpombrio** [comment] 2019-04-01 22:04
Well done tracking this down! Finding the root cause seems tractable now, when it didn't before.

**Comment by blerner** [comment] 2019-04-02 01:54
One thing that jumps out at me: it looks like you've eliminated the `define("jglr/rnglr", ["jglr/cyclicJSON"], function(cycle) { ... })` wrapper around the rnglr and jglr modules, and now they're top-level functions.  So `Grammar` is now stuck in the global scope, which may easily have screwed up some scoping thing...  It's also worth adding a debug-print of the `rule` that's attempting to be looked up and have its action applied, to see whether that's gotten garbled somehow.

**Comment by prestontw** [comment] 2019-04-03 17:03
Tracked root cause to https://github.com/bootstrapworld/wescheme-js/blob/master/src/lex.js#L144

**Comment by schanzer** [comment] 2019-04-04 12:39
Should be fixed by https://github.com/bootstrapworld/wescheme-js/commit/d89b585d2524b894d5da96958f235434f88220a6

**Comment by prestontw** [comment] 2019-04-04 16:44
Confirming fix! Thank you, @schanzer!

**Closed** 2019-04-04 19:00 UTC
