### ISSUE TITLE
Patching code doesn't mark things dirty that should be

### ISSUE THREAD

**Issue by sorawee** [bootstrapworld/codemirror-blocks#156] opened 2018-08-30 17:34 UTC
1)

Consider:

```
(define x)
1
```

Drag `1` into the usual position. I would expect to get `(define x 1)`. While `1` is gone, the unknown block is left unchanged (i.e., not changed to the define block).

---------------------------

2) 

Consider:

```
(define x 1 2)
```

Drag `2` off to outside. While a literal `2` is created outside, the unknown block is left unchanged.

----------------------------

3) 

Consider:

```
(cond a b)
```

Drag `b` off. We will see the same problem as 2)

----------------------------

4)

Consider:

```
(cond 1) (2 3)
```

Drag `(2 3)` in. Interestingly, it works fine on master, but it doesn't work on http://www.bootstrapworld.org/preview/testing/cow-game.html with the same problem as 1)

**Comment by schanzer** [comment] 2018-08-30 18:35
This is actually a dupe of #119 : my patching algorithm is not aggressive enough about marking things as dirty.

**Comment by sorawee** [comment] 2018-08-30 18:37
Close as dup then

**Comment by schanzer** [comment] 2018-08-30 18:42
Let's use this one and close the other.

**Closed** 2019-02-27 16:38 UTC
Labels: reactify-fixed
