### ISSUE TITLE
Multiple-delete doesn't

### ISSUE THREAD

**Issue by justinpombrio** [bootstrapworld/codemirror-blocks#181] opened 2019-01-17 17:46 UTC
If you select multiple block and then delete them or cut them, the first block goes away but the rest are transformed into plain text.

The issue seems to be around `codeMirror.js`. Here's what it looks like is happening:

- The `tmpCM` codemirror instance receives two `replaceRange` commands, and does them.
- The `global.cm` codemirror instance, which starts out with the same text, receives the same two `replaceRange` commands, and does _only the first one_.
- Hilarity ensues, now that the AST and the code are out of sync.

**Comment by justinpombrio** [comment] 2019-01-17 21:01
Upon committing the operation of deleting two lines, `react-codemirror-2/Controlled` fires the `onBeforeChange` event twice, as expected, and with the correct values. It also fires the `onChange` event once, with the wrong value (only one of the two lines is deleted). And after the whole ordeal, our global cm instance has only deleted one of the two lines.

**Comment by justinpombrio** [comment] 2019-01-24 03:30
Here's an google sheet:

- [Debugging multiple-delete bug](https://docs.google.com/spreadsheets/d/1Ce6sQMJPkF43Ts2YpC9xlWfmuNogV-gZ5K5nNjkdWXc/edit?usp=sharing) 

showing the order in which various things happen. It's all fine, including up through when `DragAndDropEditor` passes the correct `value={this.props.value}` to the `<CodeMirror.../>` element, but after that somehow CodeMirror's value is incorrect and only contains one of the two deletions.

**Comment by schanzer** [comment] 2019-01-24 17:37
OK, did some poking around - I think my CodeMirror knowledge will come in handy here: _the code assumes that the `changes` object is immutable, and that it can be passed to one editor and then to another and have the same effect.

If we print out `data` inside the `handleChange` method in ToggleEditor, we can see what the `changes` object looks like. Notice that the `canceled` property is set to `true`, which will result in the operation not being processed at all! I suspect this is happening because `tmpCM` is marking completed operations as canceled.

Manually setting `data.canceled = false` appears to resolve the issue.

**Comment by schanzer** [comment] 2019-01-31 20:56
This now appears to be fixed.

**Comment by schanzer** [comment] 2019-02-06 12:25
Confirmed fixed. Closing.

**Closed by schanzer** 2019-02-06 12:25 UTC
